title: The Journey to conquer AI 
author: Ashish Ratnawat 
email: your- ashishratnawat452@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there, this is my blog for AI
# social links
twitter_username: ashish_ratn
github_username:  ashish-ratn

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
